name = "WarioWare, Inc. - Mega Microgames$!"
home = "https://discord.com/channels/731205301247803413/1537579474793668668"
default_url = "https://github.com/TheLX5/Archipelago/releases/download/wariowareinc-v{{version}}/wario_ware_inc.apworld"

[versions]
"1.0.0" = {}
